needs changelog:
- all:
  - '!docs/changelog.rst'
  any:
  - '(include|pybind11|tools)/**/*'

docs:
- any:
  - 'docs/**/*.rst'
  - '!docs/changelog.rst'
  - '!docs/upgrade.rst'

ci:
- '.github/workflows/*.yml'
